# Generated by Django 3.0.3 on 2020-02-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Abstract', models.CharField(max_length=200)),
                ('FullText', models.CharField(max_length=1000)),
                ('ImageUrl', models.CharField(max_length=100)),
                ('PublishDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
