# Generated by Django 3.0.3 on 2020-02-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='UrlTitle',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
