# Generated by Django 3.0.3 on 2020-02-15 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0002_auto_20200215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Abstract',
            field=models.CharField(default='Some Abstract', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='FullText',
            field=models.CharField(max_length=1000, verbose_name='Full,Please'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ImageUrl',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 23, 15, 38, 20101, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(default='Cool Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='UrlTitle',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
