# Generated by Django 3.0.3 on 2020-02-15 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0004_auto_20200215_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 23, 19, 57, 136613, tzinfo=utc), verbose_name='date published'),
        ),
    ]
