# Generated by Django 3.0.3 on 2020-02-16 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0005_auto_20200215_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='FullText',
            field=models.CharField(default='', max_length=1000, verbose_name='FullText'),
        ),
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 13, 13, 44, 337737, tzinfo=utc), verbose_name='PublishDate'),
        ),
    ]
