# Generated by Django 3.0.3 on 2020-02-17 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0006_auto_20200216_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 23, 55, 52, 62781, tzinfo=utc), verbose_name='PublishDate'),
        ),
    ]
