# Generated by Django 3.0.3 on 2020-02-18 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nserver', '0007_auto_20200218_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PublishDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 0, 20, 0, 252521, tzinfo=utc), verbose_name='PublishDate'),
        ),
    ]
